const LOGIN = 'LOGIN';
const FAVORITAR = 'FAVORITAR';
const DESFAVORITAR = 'DESFAVORITAR';
const CARREGAR_ANIMAIS = 'CARREGAR_ANIMAIS';
const SET_LOADING = 'SET_LOADING';
const INCLUIR_ANIMAL = 'INCLUIR_ANIMAL';
const ALTERAR_ANIMAL = 'ALTERAR_ANIMAL';
const EXCLUIR_ANIMAL = 'EXCLUIR_ANIMAL';

export {
  LOGIN,
  FAVORITAR,
  DESFAVORITAR,
  CARREGAR_ANIMAIS,
  SET_LOADING,
  INCLUIR_ANIMAL,
  ALTERAR_ANIMAL,
  EXCLUIR_ANIMAL,
};
